extends: stylelint-config-standard-scss
plugins:
  - stylelint-scss
  - stylelint-order
rules:
  # scss/at-import-no-partial-leading-underscore: null
  string-quotes: single # We use single quotes in SCSS
  declaration-block-no-redundant-longhand-properties: null # We prefer lonhand properties for clarity in SCSS
  selector-class-pattern: null # We're not too stict about selector class pattern
  max-line-length: null # Lets not limit line length at this point
  declaration-empty-line-before: never # No need for empty line before declaration
  order/properties-alphabetical-order: true # We're following alphabetical order in properties
  custom-property-pattern: "^([a-z][a-z0-9]*)(--?[a-z0-9]+)*$" # kebab-case pattern with allowed bem-like double --
  color-hex-length: 'long'
  font-family-name-quotes: 'always-unless-keyword'
  value-keyword-case: null # This was causing too much hassle and making thing like currentColor hard to read
  max-nesting-depth:
    - 3 # we should finetune this to be lower
    - ignore:
        - pseudo-classes
  number-max-precision:
    - 4
    - ignoreUnits:
        - '%' # Sometimes we need more specific values to be able to round to even pixels with percentages
overrides:
  - files:
      - '**/__index.scss'
      - '**/_hds.scss'
      - '**/ckeditor.scss'
      - '**/color-palette.scss'
      - '**/component-library.scss'
      - '**/environment-indicator.scss'
      - '**/styles.scss'
    rules:
      scss/at-import-no-partial-leading-underscore: null
