export const defaultSelectTheme = {
  '--focus-outline-color': 'var(--color-coat-of-arms)',
  '--menu-item-border-color-focus': 'var(--color-coat-of-arms)',
  '--menu-item-background-color-hover': 'var(--color-black-5)',
  '--menu-item-background-color-selected': 'var(--color-black-90)',
  '--menu-item-background-color-selected-hover': 'var(--color-black-80)',
  '--menu-item-color-hover': 'var(--color-black-90)',
  '--menu-item-color-selected': 'var(--color-white)',
  '--menu-item-color-selected-hover': 'var(--color-white)',
  '--menu-item-icon-color-selected': 'var(--color-white)',
  '--text-color-focus-outline': 'var(--color-coat-of-arms)',
  '--computed-assistive-color': 'var(--color-black-60)',
} as const;

export const defaultMultiSelectTheme = {
  '--checkbox-background-selected': 'var(--color-black-90)',
  '--checkbox-background-hover': 'var(--color-black-90)',
  '--checkbox-border-color-selected': 'var(--color-black-90)',
  '--checkbox-border-color-selected-hover': 'var(--color-black-90)',
  '--checkbox-border-color-selected-focus': 'var(--color-black-90)',
  '--focus-outline-color': 'var(--color-coat-of-arms)',
  '--menu-item-border-color-focus': 'var(--color-coat-of-arms)',
  '--menu-item-background-color-hover': 'var(--color-black-5)',
  '--menu-item-background-color-selected': 'var(--color-white)',
  '--menu-item-background-color-selected-hover': 'var(--color-black-5)',
  '--menu-item-color-hover': 'var(--color-black-90)',
  '--menu-item-color-selected': 'var(--color-black-90)',
  '--menu-item-color-selected-hover': 'var(--color-black-90)',
  '--text-color-focus-outline': 'var(--color-coat-of-arms)',
  '--computed-assistive-color': 'var(--color-black-60)',
} as const;
