export const defaultSelectTheme = {
  '--checkbox-background-selected': 'var(--hdbt-color-black)',
  '--checkbox-background-hover': 'var(--hdbt-color-black)',
  '--checkbox-border-color-selected': 'var(--color-white)',
  '--checkbox-border-color-selected-hover': 'var(--color-white)',
  '--checkbox-border-color-selected-focus': 'var(--color-white)',
  '--focus-outline-color': 'var(--hdbt-color-black)',
  '--menu-item-border-color-focus': 'var(--hdbt-color-black)',
  '--menu-item-background-color-hover': 'var(--color-black-5)',
  '--menu-item-background-color-selected': 'var(--hdbt-color-black)',
  '--menu-item-background-color-selected-hover': 'var(--color-black-80)',
  '--menu-item-color-hover': 'var(--hdbt-color-black)',
  '--menu-item-color-selected': 'var(--color-white)',
  '--menu-item-color-selected-hover': 'var(--color-white)',
  '--menu-item-icon-color-selected': 'var(--color-white)',
  '--text-color-focus-outline': 'var(--hdbt-color-black)',
} as const;
