import OntologyDetailMap from '../types/OntologyDetailsMap';

const ontologyDetailsIdsToLang: OntologyDetailMap = {
  a1: {
    15: Drupal.t('English', {}, { context: 'TPR Ontologyword details schools' }),
    16: Drupal.t('Spanish', {}, { context: 'TPR Ontologyword details schools' }),
    17: Drupal.t('Hebrew', {}, { context: 'TPR Ontologyword details schools' }),
    18: Drupal.t('Italian', {}, { context: 'TPR Ontologyword details schools' }),
    19: Drupal.t('Chinese', {}, { context: 'TPR Ontologyword details schools' }),
    20: Drupal.t('Latin', {}, { context: 'TPR Ontologyword details schools' }),
    21: Drupal.t('French', {}, { context: 'TPR Ontologyword details schools' }),
    22: Drupal.t('Swedish', {}, { context: 'TPR Ontologyword details schools' }),
    23: Drupal.t('German', {}, { context: 'TPR Ontologyword details schools' }),
    24: Drupal.t('Finnish', {}, { context: 'TPR Ontologyword details schools' }),
    25: Drupal.t('Russian', {}, { context: 'TPR Ontologyword details schools' }),
    26: Drupal.t('Estonian', {}, { context: 'TPR Ontologyword details schools' }),
  },
  a2: {
    27: Drupal.t('English', {}, { context: 'TPR Ontologyword details schools' }),
    28: Drupal.t('Spanish', {}, { context: 'TPR Ontologyword details schools' }),
    29: Drupal.t('Hebrew', {}, { context: 'TPR Ontologyword details schools' }),
    30: Drupal.t('Italian', {}, { context: 'TPR Ontologyword details schools' }),
    31: Drupal.t('Chinese', {}, { context: 'TPR Ontologyword details schools' }),
    32: Drupal.t('Latin', {}, { context: 'TPR Ontologyword details schools' }),
    33: Drupal.t('French', {}, { context: 'TPR Ontologyword details schools' }),
    34: Drupal.t('Swedish', {}, { context: 'TPR Ontologyword details schools' }),
    35: Drupal.t('German', {}, { context: 'TPR Ontologyword details schools' }),
    36: Drupal.t('Finnish', {}, { context: 'TPR Ontologyword details schools' }),
    37: Drupal.t('Russian', {}, { context: 'TPR Ontologyword details schools' }),
    38: Drupal.t('Estonian', {}, { context: 'TPR Ontologyword details schools' }),
  },
  b1: {
    101: Drupal.t('English', {}, { context: 'TPR Ontologyword details schools' }),
    102: Drupal.t('Spanish', {}, { context: 'TPR Ontologyword details schools' }),
    103: Drupal.t('Hebrew', {}, { context: 'TPR Ontologyword details schools' }),
    104: Drupal.t('Italian', {}, { context: 'TPR Ontologyword details schools' }),
    105: Drupal.t('Chinese', {}, { context: 'TPR Ontologyword details schools' }),
    106: Drupal.t('Latin', {}, { context: 'TPR Ontologyword details schools' }),
    107: Drupal.t('French', {}, { context: 'TPR Ontologyword details schools' }),
    108: Drupal.t('Swedish', {}, { context: 'TPR Ontologyword details schools' }),
    109: Drupal.t('German', {}, { context: 'TPR Ontologyword details schools' }),
    110: Drupal.t('Finnish', {}, { context: 'TPR Ontologyword details schools' }),
    111: Drupal.t('Russian', {}, { context: 'TPR Ontologyword details schools' }),
    112: Drupal.t('Estonian', {}, { context: 'TPR Ontologyword details schools' }),
  },
  b2: {
    113: Drupal.t('English', {}, {context: 'TPR Ontologyword details schools'}),
    114: Drupal.t('Spanish', {}, {context: 'TPR Ontologyword details schools'}),
    115: Drupal.t('Hebrew', {}, {context: 'TPR Ontologyword details schools'}),
    116: Drupal.t('Italian', {}, {context: 'TPR Ontologyword details schools'}),
    117: Drupal.t('Chinese', {}, {context: 'TPR Ontologyword details schools'}),
    118: Drupal.t('Latin', {}, {context: 'TPR Ontologyword details schools'}),
    119: Drupal.t('French', {}, {context: 'TPR Ontologyword details schools'}),
    120: Drupal.t('Swedish', {}, {context: 'TPR Ontologyword details schools'}),
    121: Drupal.t('German', {}, {context: 'TPR Ontologyword details schools'}),
    122: Drupal.t('Finnish', {}, {context: 'TPR Ontologyword details schools'}),
    123: Drupal.t('Russian', {}, {context: 'TPR Ontologyword details schools'}),
    124: Drupal.t('Estonian', {}, {context: 'TPR Ontologyword details schools'}),
  },
  bilingualEducation: {
    149: Drupal.t('Teaching in English', {}, { context: 'TPR Ontologyword details schools' }),
    150: Drupal.t('Teaching in English', {}, { context: 'TPR Ontologyword details schools' }),
    293: Drupal.t('Language immersion (English)', {}, { context: 'TPR Ontologyword details schools' }),
    295: Drupal.t('Language immersion (Swedish)', {}, { context: 'TPR Ontologyword details schools' }),
    297: Drupal.t('Language immersion (German)', {}, { context: 'TPR Ontologyword details schools' }),
    904: Drupal.t('Finnish-English', {}, { context: 'TPR Ontologyword details schools' }),
    905: Drupal.t('Finnish-Chinese', {}, { context: 'TPR Ontologyword details schools' }),
    906: Drupal.t('Finnish-Spanish', {}, { context: 'TPR Ontologyword details schools' }),
    907: Drupal.t('Finnish-Northern Sami', {}, { context: 'TPR Ontologyword details schools' }),
    908: Drupal.t('Finnish-Estonian', {}, { context: 'TPR Ontologyword details schools' }),
    909: Drupal.t('Finnish-Russian', {}, { context: 'TPR Ontologyword details schools' }),
    910: Drupal.t('Language-enriched education (Finnish-English)', {}, { context: 'TPR Ontologyword details schools' }),
    911: Drupal.t('Language-enriched education (Finnish-Russian)', {}, { context: 'TPR Ontologyword details schools' }),
    1041: Drupal.t('Finnish-Swedish', {}, { context: 'TPR Ontologyword details schools' }),
  },
};

export default ontologyDetailsIdsToLang;
