const context = 'TPR Ontologyword details schools';

const ontologyDetailsIdsToLang: any = {
  15: Drupal.t('English', {}, { context }),
  16: Drupal.t('Spanish', {}, { context }),
  17: Drupal.t('Hebrew', {}, { context }),
  18: Drupal.t('Italian', {}, { context }),
  19: Drupal.t('Chinese', {}, { context }),
  20: Drupal.t('Latin', {}, { context }),
  21: Drupal.t('French', {}, { context }),
  22: Drupal.t('Swedish', {}, { context }),
  23: Drupal.t('German', {}, { context }),
  24: Drupal.t('Finnish', {}, { context }),
  25: Drupal.t('Russian', {}, { context }),
  26: Drupal.t('Estonian', {}, { context }),
  27: Drupal.t('English', {}, { context }),
  28: Drupal.t('Spanish', {}, { context }),
  29: Drupal.t('Hebrew', {}, { context }),
  30: Drupal.t('Italian', {}, { context }),
  31: Drupal.t('Chinese', {}, { context }),
  32: Drupal.t('Latin', {}, { context }),
  33: Drupal.t('French', {}, { context }),
  34: Drupal.t('Swedish', {}, { context }),
  35: Drupal.t('German', {}, { context }),
  36: Drupal.t('Finnish', {}, { context }),
  37: Drupal.t('Russian', {}, { context }),
  38: Drupal.t('Estonian', {}, { context }),
  101: Drupal.t('English', {}, { context }),
  102: Drupal.t('Spanish', {}, { context }),
  103: Drupal.t('Hebrew', {}, { context }),
  104: Drupal.t('Italian', {}, { context }),
  105: Drupal.t('Chinese', {}, { context }),
  106: Drupal.t('Latin', {}, { context }),
  107: Drupal.t('French', {}, { context }),
  108: Drupal.t('Swedish', {}, { context }),
  109: Drupal.t('German', {}, { context }),
  110: Drupal.t('Finnish', {}, { context }),
  111: Drupal.t('Russian', {}, { context }),
  112: Drupal.t('Estonian', {}, { context }),
  113: Drupal.t('English', {}, { context }),
  114: Drupal.t('Spanish', {}, { context }),
  115: Drupal.t('Hebrew', {}, { context }),
  116: Drupal.t('Italian', {}, { context }),
  117: Drupal.t('Chinese', {}, { context }),
  118: Drupal.t('Latin', {}, { context }),
  119: Drupal.t('French', {}, { context }),
  120: Drupal.t('Swedish', {}, { context }),
  121: Drupal.t('German', {}, { context }),
  122: Drupal.t('Finnish', {}, { context }),
  123: Drupal.t('Russian', {}, { context }),
  124: Drupal.t('Estonian', {}, { context }),
  293: Drupal.t('Language immersion (English)', {}, { context }),
  295: Drupal.t('Language immersion (Swedish)', {}, { context }),
  297: Drupal.t('Language immersion (German)', {}, { context }),
  904: Drupal.t('Finnish-English', {}, { context }),
  905: Drupal.t('Finnish-Chinese', {}, { context }),
  906: Drupal.t('Finnish-Spanish', {}, { context }),
  907: Drupal.t('Finnish-Northern Sami', {}, { context }),
  908: Drupal.t('Finnish-Estonian', {}, { context }),
  909: Drupal.t('Finnish-Russian', {}, { context }),
  910: Drupal.t('Language-enriched education (Finnish-English)', {}, { context }),
  911: Drupal.t('Language-enriched education (Finnish-Russian)', {}, { context })
};

export default ontologyDetailsIdsToLang;
