<?php

use Drupal\hdbt_default\Entity\RemoteVideo;

function hdbt_default_template_preprocess_default_variables_alter(&$variables) {
  $variables['koro'] = _hdbt_get_settings('koro');
  $variables['theme_color'] = _hdbt_get_settings('theme_color');
  $variables['image_placeholder'] = _hdbt_get_settings('default_icon');
  $language = Drupal::languageManager()->getCurrentLanguage(\Drupal\Core\Language\LanguageInterface::TYPE_CONTENT);
  $variables['current_langcode'] = $language->getId();
  $variables['current_language'] = $language->getName();

  $defaultLanguageResolver = Drupal::service('helfi_api_base.default_language_resolver');
  $variables['alternative_language'] = $defaultLanguageResolver->isAltLanguage($language->getId());

  if ($variables['alternative_language']) {
    $attributes = $defaultLanguageResolver->getFallbackLangAttributes();
    $variables['lang_attributes']['fallback_lang'] = $attributes['lang'];
    $variables['lang_attributes']['fallback_dir'] = $attributes['dir'];
  }

  // Toggle between global and local navigation in twig templates.
  $variables['use_global_navigation'] = \Drupal::moduleHandler()
    ->moduleExists('helfi_navigation');
  $variables['#attached']['drupalSettings']['hdbt']['global_menu'] = \Drupal::moduleHandler()
    ->moduleExists('helfi_navigation');

  // @todo Fix this to be independent block as well.
  $variables['#attached']['drupalSettings']['hdbt']['search_dropdown'] = \Drupal::moduleHandler()
    ->moduleExists('helfi_navigation');

  // Apply override for the theme color.
  if (!empty($theme_color = hdbt_get_theme_color_override())) {
    $variables['theme_color'] = $theme_color;
  }

  // Add helfi-environment name.
  if (\Drupal::hasService('helfi_api_base.environment_resolver')) {
    try {
      $id = \Drupal::service('helfi_api_base.environment_resolver')
        ->getActiveEnvironment()
        ->getId();
      $variables['#attached']['drupalSettings']['helfi_instance_name'] = $id;
    }
    catch (\Exception $exception) {
    }
  }

  // Required for allowing subtheming for HDBT theme.
  $variables['active_theme'] = $active_theme = \Drupal::theme()->getActiveTheme()->getName();
  $variables['theme_prefix'] = $active_theme !== 'hdbt' ? $active_theme : '';
}

function _hdbt_get_settings(string $setting, string $group = 'site_settings'): string|NULL {
  return Drupal::config('hdbt_admin_tools.site_settings')
    ?->getOriginal("$group.$setting", FALSE);
}

function hdbt_default_entity_bundle_info_alter(array &$bundles): void {
  if (isset($bundles['media'])) {
    $bundles['media']['remote_video']['class'] = RemoteVideo::class;
    $bundles['media']['hel_map']['class'] = \Drupal\hdbt_default\Entity\HelMap::class;
  }
}
