<?php
// phpcs:ignoreFile

/**
 * @file
 * Contains theme defaults.
 */

use Drupal\Core\Entity\ContentEntityInterface;
use Drupal\Core\Language\LanguageInterface;

/**
 * Implement hook_default_template_preprocess_default_variables_alter().
 */
function hdbt_default_template_preprocess_default_variables_alter(&$variables) {
  $variables['koro'] = _hdbt_get_settings('koro');
  $variables['theme_color'] = _hdbt_get_settings('theme_color');
  $variables['image_placeholder'] = _hdbt_get_settings('default_icon');
  $language = Drupal::languageManager()->getCurrentLanguage(LanguageInterface::TYPE_CONTENT);
  $variables['current_langcode'] = $language->getId();
  $variables['current_language'] = $language->getName();

  $defaultLanguageResolver = Drupal::service('helfi_api_base.default_language_resolver');
  $variables['alternative_language'] = $defaultLanguageResolver->isAltLanguage($language->getId());

  if ($variables['alternative_language']) {
    $attributes = $defaultLanguageResolver->getFallbackLangAttributes();
    $variables['lang_attributes']['fallback_lang'] = $attributes['lang'];
    $variables['lang_attributes']['fallback_dir'] = $attributes['dir'];
  }

  // Toggle between global and local navigation in twig templates.
  $variables['use_global_navigation'] = \Drupal::moduleHandler()
    ->moduleExists('helfi_navigation');
  $variables['#attached']['drupalSettings']['hdbt']['global_menu'] = \Drupal::moduleHandler()
    ->moduleExists('helfi_navigation');

  // @todo Fix this to be independent block as well.
  $variables['#attached']['drupalSettings']['hdbt']['search_dropdown'] = \Drupal::moduleHandler()
    ->moduleExists('helfi_navigation');

  // Apply override for the theme color.
  if (!empty($theme_color = _hdbt_get_theme_color_override())) {
    $variables['theme_color'] = $theme_color;
  }

  // Add helfi-environment name.
  if (\Drupal::hasService('helfi_api_base.environment_resolver')) {
    try {
      $id = \Drupal::service('helfi_api_base.environment_resolver')
        ->getActiveEnvironment()
        ->getId();
      $variables['#attached']['drupalSettings']['helfi_instance_name'] = $id;
    }
    catch (\Exception $exception) {
    }
  }

  // Required for allowing subtheming for HDBT theme.
  $variables['active_theme'] = $active_theme = \Drupal::theme()->getActiveTheme()->getName();
  $variables['theme_prefix'] = $active_theme !== 'hdbt' ? $active_theme : '';
}

/**
 * Retrieve possible theme color palette override.
 */
function _hdbt_get_theme_color_override(): string|FALSE {
  $color = &drupal_static(__FUNCTION__);

  if (!isset($color)) {
    $color = FALSE;
    if (Drupal::moduleHandler()->moduleExists('hdbt_admin_tools')) {
      $page_entity = hdbt_admin_tools_get_page_entity();
      if (
        !empty($page_entity) &&
        $page_entity instanceof ContentEntityInterface &&
        $page_entity->hasField('color_palette') &&
        !empty($page_entity->color_palette->value)
      ) {
        $color = $page_entity->color_palette->value;
      }
    }
  }
  return $color;
}

/**
 * Get hdbt settings.
 *
 * @param string $setting
 *   Settings to get.
 * @param string $group
 *   The group.
 *
 * @return string|NULL
 *   The setting.
 */
function _hdbt_get_settings(string $setting, string $group = 'site_settings'): string|null {
  return Drupal::config('hdbt_admin_tools.site_settings')
    ?->getOriginal("$group.$setting", FALSE);
}

/**
 * Helper function to hdbt theme path.
 */
function _hdbt_get_theme_path(): string {
  /** @var \Drupal\Core\File\FileUrlGeneratorInterface $service */
  $service = \Drupal::service('file_url_generator');

  // Add theme path to as variable.
  $theme = \Drupal::service('theme_handler')->getTheme('hdbt');
  return $service->generate($theme->getPath())
    ->toString(TRUE)->getGeneratedUrl();
}
