const IndexFields = {
  LANGUAGE: '_language',
  EMPLOYMENT: 'field_employment',
  EMPLOYMENT_ID: 'employment_id',
  EMPLOYMENT_TYPE: 'field_employment_type',
  EMPLOYMENT_TYPE_ID: 'employment_type_id',
  EMPLOYMENT_SEARCH_ID: 'employment_search_id',
  ENTITY_TYPE: 'entity_type',
  JOB_DURATION: 'field_job_duration',
  NID: 'nid',
  NUMBER_OF_JOBS: 'field_jobs',
  ORGANIZATION: 'field_organization',
  ORGANIZATION_NAME: 'field_organization_name',
  POSTAL_AREA: 'field_postal_area',
  POSTAL_CODE: 'field_postal_code',
  PROMOTED: 'field_promoted',
  PUBLICATION_STARTS: 'field_publication_starts',
  RECRUITMENT_ID: 'field_recruitment_id',
  RECRUITMENT_TYPE: 'field_recruitment_type',
  TASK_AREA: 'field_task_area',
  TASK_AREA_ID: 'task_area_id',
  TASK_AREA_EXTERNAL_ID: 'task_area_external_id',
  LANGCODE: 'langcode',
  SEARCH_ID: 'field_search_id',
  STATUS: 'status',
  TID: 'tid',
  TITLE: 'title',
  UNPUBLISH_ON: 'unpublish_on',
  UUID: 'uuid',
};

export default IndexFields;
