on: [push]
name: Build new release
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Read .nvmrc
        id: node_version
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ steps.node_version.outputs.NODE_VERSION }}

      - name: Install dependencies
        run: |
          npm i
          npm run build
          npm run postinstall
          zip latest.zip *.json dist/ *.theme *.yml *.md *.png templates/
          tar -zcf latest.tar.gz *.json dist/ *.theme .yml *.md *.png templates/

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Latest version"
          files: |
            latest.zip
            latest.tar.gz
