on:
  push:
    branches:
      - 5.x
      - main
name: Build assets
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Set variables
        run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_ENV

      - name: Build assets
        run: docker run --rm -v $(pwd):/app -w /app node:${NODE_VERSION}-alpine ""npm install && npm run build""

      - name: Commit changed assets
        run: |
          if [[ $(git status --porcelain) ]]; then
            git config --global user.name github-actions
            git config --global user.email github-actions@github.com
            git add dist
            git commit -m "CI built assets"
            git push
          fi


