on:
  pull_request:
    types: [opened, synchronize]
name: Build assets
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Set variables
        run: echo "DRUPAL_ROOT=$HOME/drupal" >> $GITHUB_ENV

      - name: Clone platform
        run: git clone https://github.com/City-of-Helsinki/drupal-helfi-platform.git $DRUPAL_ROOT

      - name: Build assets
        run: |
          docker run  --rm --name helfi-node-18.15.0-alpine -v $(pwd):/app -w /app node:18.15.0-alpine "ls -la"

