on: [push]
name: Lint
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: $(cat .nvmrc)

      - name: Install dependencies
        run: |
          npm i
          npx husky i
