on: [push]
name: Lint
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Read .nvmrc
        id: node_version
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ steps.node_version.outputs.NODE_VERSION }}

      - name: Install dependencies
        run: |
          npm i
          npx husky i

      - name: Run JS linter
        run: ./node_modules/eslint/bin/eslint.js src/js/*.js
