on: [push]
name: Update Drupal repository
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger build
        run: |
          curl --request POST \
          --url https://api.github.com/repos/city-of-helsinki/drupal-repository/actions/workflows/build.yml/dispatches \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{"ref": "${{ github.sha }}"}'
