on:
  pull_request:
  push:
    branches:
      - main
env:
  SIMPLETEST_DB: mysql://drupal:drupal@db:3306/drupal
name: Visual regression tests
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set variables
        run: echo "DRUPAL_ROOT=$HOME/drupal" >> $GITHUB_ENV

      - name: Parse $THEME_NAME from composer.json
        run: echo "THEME_NAME=$(cat composer.json | jq -r .name | awk -F/ '{print $NF}')" >> $GITHUB_ENV

      - name: Clone platform
        run: git clone https://github.com/City-of-Helsinki/drupal-helfi-platform.git $DRUPAL_ROOT

      - name: Install and start Stonehenge
        run: |
          git clone -b 4.x https://github.com/druidfi/stonehenge.git ~/stonehenge
          cd ~/stonehenge && make up

      - name: Build project
        working-directory: ${{ env.DRUPAL_ROOT }}
        run: |
          composer config repositories.5 path $GITHUB_WORKSPACE
          composer require drupal/$THEME_NAME -W

      - name: Start project
        working-directory: ${{ env.DRUPAL_ROOT }}
        run: docker compose up -d --wait

      - name: Wait for Database to wake up
        working-directory: ${{ env.DRUPAL_ROOT }}
        run: |
          counter=0
          until [ $counter -gt 5 ]
          do
            if [[ $(drush sql:connect) -e '\q' ]]; then
              break
            fi
            ((counter++))
            sleep 2
          done

      - name: Setup Drupal
        working-directory: ${{ env.DRUPAL_ROOT }}
        run: |
          mkdir public/sites/default/files -p && chmod 777 public/sites/default -R
          docker compose exec app bash -c "ls -la public/themes/contrib"
          docker compose exec app bash -c "drush si minimal -y"
          docker compose exec app bash -c "drush en helfi_test_content -y"

      - name: Run tests
        working-directory: ${{ env.DRUPAL_ROOT }}
        run: curl https://mysite.docker.so

